### ISSUE TITLE
Rename master -> main

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/vault-plugin-secrets-gcp#117]
I lack the permissions to do it myself, but could someone rename the default branch from master -> main? /cc @kalafut

**Comment by kalafut** [comment]
Hey Seth. Yep, will do shortly. We're finishing up review on a large PR ATM and while the GitHub branch renaming has worked seamlessly the times I've used it, I'm gonna err on the side of landing this PR with its 90 comments first and then do the rename.

**Comment by sethvargo** [comment]
Got it - is that #107?

**Comment by kalafut** [comment]
Yeah

**Comment by sethvargo** [comment]
Cool - let me know if I can help. I'm not sure the approach in #107 is the best approach for adding static service accounts, especially given some of the newer GCP APIs. Where is the best place to chat about that?

**Comment by kalafut** [comment]
@sethvargo Pinged you on slack

**Comment by kalafut** [comment]
Branch renamed.
