### ISSUE TITLE
Error using gcp static-account

### ISSUE THREAD

**Issue by shona1ikea** [hashicorp/vault-plugin-secrets-gcp#120]
Getting error as below  when I tried using gcp static account option:  

Error writing data to gcp/static-account/localvault: Error making API request.
vault write gcp/static-account/localvault service_account_email="sample@winged-math-322413.iam.gserviceaccount.com" secret_type="service_account_key" bindings=@bindings.hcl

URL: PUT http://127.0.0.1:8200/v1/gcp/static-account/localvault
Code: 404. Errors:

* 1 error occurred:
        * unsupported path

My vault status: vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.7.0
Storage Type    inmem
Cluster Name    vault-cluster-a6b073e3
Cluster ID      bfd42a26-cd8b-a40d-ef21-994d69bcdd10
HA Enabled      false

roleset is working fine. But static-account is giving the above error.

**Comment by davidmontoyago** [comment]
Hi @shona1ikea, this feature was released with [vault 1.8.0](https://github.com/hashicorp/vault/releases/tag/v1.8.0). Try upgrading your vault server.

**Comment by shona1ikea** [comment]
I also need to implement this in our enterprise vault :

Version                                1.6.5+prem

If the feature is not supported here also , do we have any option to manage key of an existing gcp service account ?

**Comment by robmonte** [comment]
Hi @shona1ikea -  As @davidmontoyago mentioned, this feature was added later into Vault 1.8. To use the static roles feature you would need to upgrade from 1.6. Thanks for being a part of the community!
