### ISSUE TITLE
Not able to remove expired lease for Access Token

### ISSUE THREAD

**Issue by jacklty** [hashicorp/vault-plugin-secrets-gcp#14]
Hi, 

I have seen many stale leases for GCP access token, and I am not able to clean them up:
```
[ERROR] secrets.system.system_6aeff124: lease revocation failed: lease_id=gcp/token/tsk8s-dde/3614e5d1-6cc2-c7cb-75eb-bd86127facd7 error="failed to revoke entry: resp: &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"googleapi: got HTTP response code 400 with body: {\n  \"error\": \"invalid_token\"\n}"}, Redirect:"", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil)} err: <nil>"
```

By the way, should these leases be removed automatically since they are not refreshable?

Thanks

**Comment by jacklty** [comment]
Hi Emily,

Yes, the lease length originally starts with 3600 for TTL. As long as it still valid, I am able to revoke it either thru command line or UI. Once it expires (TTL would show negative), I am not able to remove it anymore (well, I was able to remove them from GCS bucket manually).

**Comment by camerondavison** [comment]
Im on vault 0.11.1  and seem to be having this same issue. It looks like this code got released with the new version of vault.


```
$ vault secrets disable gcp
Error disabling secrets engine at gcp/: Error making API request.

URL: DELETE https://********/v1/sys/mounts/gcp
Code: 400. Errors:

* failed to revoke "gcp/token/*********/485213a4-233d-cb9a-80cf-8c98883feb0d" (1 / 42): failed to revoke entry: resp: &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"googleapi: got HTTP response code 400 with body: {\n  \"error\": \"invalid_token\"\n}"}, Redirect:"", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil)} err: <nil>
```

if i try to revoke that one lease using `vault revoke lease <lease id>` it says that it queues it. 

but then I see the following ERROR in the logs
```
2018-09-15T00:06:00.951Z [ERROR] expiration: failed to revoke lease: lease_id=gcp/token/*************/485213a4-233d-cb9a-80cf-8c98883feb0d error="failed to revoke entry: resp: &logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"error":"googleapi: got HTTP response code 400 with body: {\n  \"error\": \"invalid_token\"\n}"}, Redirect:"", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil)} err: <nil>"
```

TTL does looks to be negative in the ui
![image](https://user-images.githubusercontent.com/165381/45579996-c0b8d300-b851-11e8-9445-a7c6eb4001fe.png)
seems like the `expires in` logic in the UI is counting up now that it is negative as well

**Comment by emilymye** [comment]
Well, this is an issue (@jeff @bk). I can add a fix to remove the error as long as it's an invalid token already, but since there will be a larger change related to the access token behavior by the time we probably release a fix that will override it, I'm not sure I should attempt to fix this right now.

**Comment by camerondavison** [comment]
is there any way to update this plugin out of band of a vault release?
