### ISSUE TITLE
Missing support for dns resource type

### ISSUE THREAD

**Issue by thuck** [hashicorp/vault-plugin-secrets-gcp#201]
Hi;

Looks like last year GCP included the possibility of per managedZone permissions on the DNS resource.  
When trying to use it with Vault I get an error:    
`* invalid resource "https://dns.googleapis.com/dns/v1/projects/PROJECT/managedZones/ZONE_NAME": unsupported resource type: projects/managedZones`

**Comment by austingebauer** [comment]
Hi @thuck, thanks for reporting this. We're taking a look at onboarding new resource types.

**Comment by tomhjp** [comment]
WIP in #211, although it has some unresolved errors blocking support for DNS APIs at the moment.

**Comment by bmaximuml** [comment]
This is fixed in: https://github.com/hashicorp/vault/pull/28089

**Comment by thuck** [comment]
Closing in favor of https://github.com/hashicorp/vault/pull/28089
