### ISSUE TITLE
The secret returned by reading the gcp token path returns zero lease_duration time

### ISSUE THREAD

**Issue by soider** [hashicorp/vault-plugin-secrets-gcp#22]
I have enabled GCP backend on the following path:
`dev/gcp/feature_name`

For some role X I have created record using the path `dev/gcp/feature_name/roleset/X` with following settings:

```
"secret_type":  "access_token",
"project":      <PROJECT_ID>,
"token_scopes": "https://www.googleapis.com/auth/cloud-platform",
"bindings":     "resource "//cloudresourcemanager.googleapis.com/projects/<PROJECT_ID>" {
       							 roles = ["roles/bigquery.dataEditor"]
      						}",
```

Whenever I try to read the secret from the vault I got token with lease_duration equals 0.

```
# wget --header 'X-Vault-Token: 7d52e719-c3bb-4fd0-9f08-6e11051fea19' http://0.0.0.0:8200/v1/dev/gcp/featurename/token/X
# cat  X
{"request_id":"3c156981-3ba3-d85b-7bee-ea55c5c0c404","lease_id":"","renewable":false,"lease_duration":0,"data":{"expires_at_seconds":1539687813,"token":"<TOKEN_VALUE>,"token_ttl":3599},"wrap_info":null,"warnings":null,"auth":null}
```

However, the correct expires at seconds is located inside the data node.

**Comment by soider** [comment]
I use vault 0.11.3

**Comment by emilymye** [comment]
In a recent release of this plugin, we decided to remove the Vault-controlled lease from OAuth tokens because we discovered that GCP OAuth tokens actually just have a fixed, non-revocable TTL of 1 hr. See https://www.vaultproject.io/docs/auth/gcp.html for more. `lease_duration` is being set to the default int value 0 (x), but the actual lifetime for the token is still included in data just in case.

**Comment by kuwas** [comment]
@soider
See also: https://github.com/hashicorp/vault-plugin-secrets-gcp/issues/18
The only to "revoke" these tokens is to overwrite the entire roleset, which in turn rotates the service account and invalidates all oauth2 tokens.

**Comment by emilymye** [comment]
@kuwas you can also actually rotate the service account, see [/rotate endpoint API docs]( https://www.vaultproject.io/api/secret/gcp/#rotate-roleset-account) - useful if you don't want to deal with bindings
