### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bmaximuml** [hashicorp/vault-plugin-secrets-gcp#222]
Hello,

#216  was recently merged in, and I'm keen to start using it!

Please could you create a new release so that I can do so?

Thanks

FYI @eh-steve

**Comment by bmaximuml** [comment]
@vinay-gopalan is this something you could help me with?

**Comment by bmaximuml** [comment]
@tomhjp would you be able to look at this? It would only need a new git tag for me to be able to open a PR on upstream vault.

**Comment by tomhjp** [comment]
Sorry @bmaximuml, wish I could help but I'm no longer a maintainer on Vault repos.

**Comment by vinay-gopalan** [comment]
Hi @bmaximuml, a new release for [GCP Secrets](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.20.0) has been issued as part of Vault's minor release process. It has been pulled into Vault, and will be made available as part of the Vault 1.18 release. Thanks, and we appreciate your patience!

**Comment by bmaximuml** [comment]
Thanks @vinay-gopalan !
