### ISSUE TITLE
How to rotate the key for access_token secret type?

### ISSUE THREAD

**Issue by jacklty** [hashicorp/vault-plugin-secrets-gcp#23]
Is there a way to tell vault to rotate the underlying key for the access_token type? or does it rotate automatically for us?

**Comment by kuwas** [comment]
The key invalidates automatically when the TTL expires. You can forcibly revoke the lease:

```
vault lease revoke (lease-id)
```

**Comment by kuwas** [comment]
@jacklty Sorry, I misread this. Do you mean the service account key that Vault uses to generate service accounts and OAuth2 tokens? Vault does not rotate that AFAIK. You can create a periodic job to call the appropriate GCP APIs or use gcloud cli to do something like this.

**Comment by emilymye** [comment]
If you're talking about rotating the key created under a role while not rotating the service account, please see 
https://www.vaultproject.io/api/secret/gcp/index.html#rotate-roleset-account-key-access_token-roleset-only-

**Comment by jacklty** [comment]
Thanks, that would do it.
