### ISSUE TITLE
Bindings update create new service account

### ISSUE THREAD

**Issue by jacklty** [hashicorp/vault-plugin-secrets-gcp#31]
Hi there,

Could we not remove the service account for bindings update? It will immediately invalidate the access token generated with previous service account.

Thanks

**Comment by emilymye** [comment]
This is the intended behavior - the roleset is meant to be a set of permissions (bindings), not a guaranteed service account with those permissions. If the permission set changes, the old credentials should be revoked immediately for security reasons. 

If you still need the old roleset credentials, you should be creating a new roleset with the new bindings, not editing the current roleset bindings.

**Comment by jacklty** [comment]
Absolutely, I totally agree if the permission set changes are substantial and meant to revoke access. However, we have a scenario that a user would like to grant additional access thru bindings (e.g. GCS buckets or objects, etc), which will require him/her to restart the application or re-validate the token for every single api calls. Creating new roleset would avoid disrupting the application/workflow, but user will still need to coordinate the roleset switch in order to gain the new permission.

**Comment by mdgreenfield** [comment]
> If the permission set changes, the old credentials should be revoked immediately for security reasons.

Hi @emilymye, I'm not sure I understand what the security reasons are here. If an authorized Vault user changes the permissions on an existing Roleset I'd expect those changes to be reflected in the existing configured GCP ServiceAccount. By revoking the ServiceAccount/credentials this means that every time a running application needs access to a new resource a new GCP Roleset needs to be created and the running application needs to be migrated to use it. The Vault Terraform provider makes it very easy to update a Vault GCP Roleset thereby invalidating the credentials and potentially causing an outage to a running application.
