### ISSUE TITLE
Cross project service accounts?

### ISSUE THREAD

**Issue by jclarksnps** [hashicorp/vault-plugin-secrets-gcp#38]
Is there any support or plans to support cross-project service accounts from rolesets?

**Comment by emilymye** [comment]
@jclarksnps sorry for the late reply, missed this issue! I'm sure you figured out the answer/a workaround but I'll answer for posterity: A service account is always bound to one project, but it can be used to manage any resources under other projects. When creating the roleset, the `project` field controls the project the service account is *created under*, and the bindings can assign that service account permissions on any resource in another project, as long as the Vault "admin" GCP creds can change the IAM policies for those projects (probably [assigned outside of Vault](https://cloud.google.com/iam/docs/granting-roles-to-service-accounts#top_of_page))

For example in the CLI command:
```
vault write gcp/roleset/my-token-roleset \
    project="owner-project" \
    secret_type="access_token"  \
    token_scopes="https://www.googleapis.com/auth/cloud-platform" \
    bindings=-<<EOF
      resource "//cloudresourcemanager.googleapis.com/projects/project-to-manage" {
        roles = ["roles/viewer"]
      }
    EOF
```

The roleset generates access tokens under a service account under project "owner-project" and gives it permissions to view project "project-to-manage".
