### ISSUE TITLE
Docs say bindings can be JSON but it's not supported.

### ISSUE THREAD

**Issue by sbunce** [hashicorp/vault-plugin-secrets-gcp#86]
The docs here say:
https://www.vaultproject.io/api-docs/secret/gcp
```
bindings (string: <required>): Bindings configuration string (expects HCL or JSON format in raw or base64-encoded string)
```

But the bindings are parsed here.
https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/master/plugin/path_role_set.go#L374

Which calls into this package, which only tries to decode as HCL.
https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/e43d20870c50f7428dead1411debcec075b35fb4/plugin/util/parse_bindings.go#L33

It seems like the two solutions would be either updating the docs, or adding JSON support.

The context where I ran into this is that I need to validate the bindings with Sentinel, and Sentinel doesn't support decoding HCL.

**Comment by sethvargo** [comment]
The HCL decoder accepts JSON:

> hcl input can come in either pure HCL format or JSON format. It can be parsed into an AST, and then decoded into a structure, or it can be decoded directly from a string into a structure.

https://godoc.org/github.com/hashicorp/hcl

**Comment by sbunce** [comment]
Oh!

Resolving. Thanks!
